player_context = """
Josh Allen, BUF QB
Patrick Mahomes II, KC QB
Jalen Hurts, PHI QB
C.J. Stroud, HOU QB
Lamar Jackson, BAL QB
Justin Jefferson, MIN WR
CeeDee Lamb, DAL WR
Ja'Marr Chase, CIN WR
Joe Burrow, CIN QB
Amon-Ra St. Brown, DET WR
Anthony Richardson, IND QB
Bijan Robinson, ATL RB
Breece Hall, NYJ RB
Marvin Harrison Jr., ARI WR
Caleb Williams, CHI QB
Garrett Wilson, NYJ WR
Kyler Murray, ARI QB
Jahmyr Gibbs, DET RB
A.J. Brown, PHI WR
Christian McCaffrey, SF RB
Puka Nacua, LAR WR
Jordan Love, GB QB
Malik Nabers, NYG WR
Jonathan Taylor, IND RB
Justin Herbert, LAC QB
Jayden Daniels, WAS QB
Trevor Lawrence, JAC QB
Tyreek Hill, MIA WR
Travis Etienne Jr., JAC RB
Chris Olave, NO WR
Sam LaPorta, DET TE
Jaylen Waddle, MIA WR
Dak Prescott, DAL QB
Drake London, ATL WR
Brandon Aiyuk, SF WR
De'Von Achane, MIA RB
Rome Odunze, CHI WR
Brock Purdy, SF QB
Saquon Barkley, PHI RB
DeVonta Smith, PHI WR
DJ Moore, CHI WR
Trey McBride, ARI TE
Nico Collins, HOU WR
Michael Pittman Jr., IND WR
Kyren Williams, LAR RB
DK Metcalf, SEA WR
Tua Tagovailoa, MIA QB
Kenneth Walker III, SEA RB
Zay Flowers, BAL WR
Rachaad White, TB RB
Isiah Pacheco, KC RB
J.J. McCarthy, MIN QB
Tee Higgins, CIN WR
James Cook, BUF RB
Jared Goff, DET QB
Jonathon Brooks, CAR RB
Mark Andrews, BAL TE
Drake Maye, NE QB
Tank Dell, HOU WR
Jordan Addison, MIN WR
Kyle Pitts, ATL TE
Brock Bowers, LV TE
Dalton Kincaid, BUF TE
George Pickens, PIT WR
Josh Jacobs, GB RB
Rashee Rice, KC WR
Jaxon Smith-Njigba, SEA WR
Bryce Young, CAR QB
Xavier Worthy, KC WR
Trey Benson, ARI RB
Deebo Samuel Sr., SF WR
Deshaun Watson, CLE QB
Rhamondre Stevenson, NE RB
Davante Adams, LV WR
Ladd McConkey, LAC WR
Jayden Reed, GB WR
Joe Mixon, HOU RB
D'Andre Swift, CHI RB
T.J. Hockenson, MIN TE
Mike Evans, TB WR
Travis Kelce, KC TE
Brian Thomas Jr., JAC WR
Derrick Henry, BAL RB
David Montgomery, DET RB
Stefon Diggs, HOU WR
Will Levis, TEN QB
Baker Mayfield, TB QB
Christian Kirk, JAC WR
Tony Pollard, TEN RB
Cooper Kupp, LAR WR
Amari Cooper, CLE WR
Terry McLaurin, WAS WR
Keon Coleman, BUF WR
George Kittle, SF TE
Javonte Williams, DEN RB
Najee Harris, PIT RB
Bo Nix, DEN QB
Tyjae Spears, TEN RB
Alvin Kamara, NO RB
Matthew Stafford, LAR QB
Diontae Johnson, CAR WR
David Njoku, CLE TE
Chris Godwin, TB WR
Evan Engram, JAC TE
Christian Watson, GB WR
Jaylen Warren, PIT RB
Zamir White, LV RB
Kirk Cousins, ATL QB
Brian Robinson Jr., WAS RB
Calvin Ridley, TEN WR
Blake Corum, LAR RB
Ricky Pearsall, SF WR
Michael Penix Jr., ATL QB
Aaron Jones, MIN RB
Jake Ferguson, DAL TE
Keenan Allen, CHI WR
Hollywood Brown, KC WR
Xavier Legette, CAR WR
Jameson Williams, DET WR
Zach Charbonnet, SEA RB
Adonai Mitchell, IND WR
Dallas Goedert, PHI TE
MarShawn Lloyd, GB RB
James Conner, ARI RB
Courtland Sutton, DEN WR
Nick Chubb, CLE RB
Pat Freiermuth, PIT TE
DeAndre Hopkins, TEN WR
Justin Fields, PIT QB
Josh Downs, IND WR
Aaron Rodgers, NYJ QB
Chase Brown, CIN RB
Daniel Jones, NYG QB
Devin Singletary, NYG RB
Jaylen Wright, MIA RB
Geno Smith, SEA QB
Jahan Dotson, WAS WR
Ben Sinnott, WAS TE
Cole Kmet, CHI TE
Austin Ekeler, WAS RB
Ja'Lynn Polk, NE WR
Roman Wilson, PIT WR
Zack Moss, CIN RB
Jerry Jeudy, CLE WR
Dalton Schultz, HOU TE
Kendre Miller, NO RB
Romeo Doubs, GB WR
Troy Franklin, DEN WR
Luke Musgrave, GB TE
Derek Carr, NO QB
Raheem Mostert, MIA RB
Jakobi Meyers, LV WR
Jerome Ford, CLE RB
Jermaine Burton, CIN WR
Ray Davis, BUF RB
Dontayvion Wicks, GB WR
Isaiah Likely, BAL TE
Tyler Lockett, SEA WR
Marvin Mims Jr., DEN WR
Joshua Palmer, LAC WR
Gabe Davis, JAC WR
Roschon Johnson, CHI RB
Tucker Kraft, GB TE
Quentin Johnston, LAC WR
Michael Mayer, LV TE
Javon Baker, NE WR
Gus Edwards, LAC RB
Kimani Vidal, LAC RB
Russell Wilson, PIT QB
Malachi Corley, NYJ WR
Chuba Hubbard, CAR RB
Tyler Allgeier, ATL RB
Michael Wilson, ARI WR
Khalil Shakir, BUF WR
Ja'Tavion Sanders, CAR TE
Mike Williams, NYJ WR
Rashid Shaheed, NO WR
Curtis Samuel, BUF WR
Jaleel McLaughlin, DEN RB
Antonio Gibson, NE RB
DeMario Douglas, NE WR
Bucky Irving, TB RB
Cade Otton, TB TE
Khalil Herbert, CHI RB
Noah Fant, SEA TE
Chigoziem Okonkwo, TEN TE
Jalen McMillan, TB WR
Audric Estime, DEN RB
Rashod Bateman, BAL WR
Brandin Cooks, DAL WR
Wan'Dale Robinson, NYG WR
Keaton Mitchell, BAL RB
Tyrone Tracy Jr., NYG RB
Ty Chandler, MIN RB
Rico Dowdle, DAL RB
Jalin Hyatt, NYG WR
Ezekiel Elliott, DAL RB
Dameon Pierce, HOU RB
Darnell Mooney, ATL WR
J.K. Dobbins, LAC RB
Hunter Henry, NE TE
Juwan Johnson, NO TE
Elijah Moore, CLE WR
Braelon Allen, NYJ RB
Greg Dulcich, DEN TE
Will Shipley, PHI RB
Luke McCaffrey, WAS WR
Treylon Burks, TEN WR
Adam Thielen, CAR WR
Theo Johnson, NYG TE
Jonathan Mingo, CAR WR
Elijah Mitchell, SF RB
Tank Bigsby, JAC RB
Jelani Woods, IND TE
Isaac Guerendo, SF RB
Dylan Laube, LV RB
Tyler Boyd, TEN WR
Alexander Mattison, LV RB
Andrei Iosivas, CIN WR
AJ Dillon, GB RB
Zay Jones, ARI WR
Taysom Hill, NO TE
Cedric Tillman, CLE WR
Gardner Minshew II, LV QB
Miles Sanders, CAR RB
Devontez Walker, BAL WR
Dawson Knox, BUF TE
Jonnu Smith, MIA TE
Kenneth Gainwell, PHI RB
Odell Beckham Jr., MIA WR
Trey Palmer, TB WR
Tyler Conklin, NYJ TE
DJ Chark Jr., LAC WR
Gerald Everett, CHI TE
A.T. Perry, NO WR
Tyler Higbee, LAR TE
D'Onta Foreman, CLE RB
Kendrick Bourne, NE WR
Malik Washington, MIA WR
Alec Pierce, IND WR
Erick All Jr., CIN TE
Rondale Moore, ATL WR
Darius Slayton, NYG WR
Jacob Cowing, SF WR
K.J. Osborn, NE WR
Mike Gesicki, CIN TE
Noah Brown, HOU WR
Greg Dortch, ARI WR
Josh Reynolds, DEN WR
Evan Hull, IND RB
Clyde Edwards-Helaire, KC RB
Isaiah Davis, NYJ RB
Samaje Perine, DEN RB
Skyy Moore, KC WR
Cade Stover, HOU TE
Jamaal Williams, NO RB
Kadarius Toney, KC WR
Rasheen Ali, BAL RB
Daniel Bellinger, NYG TE
Sam Darnold, MIN QB
Israel Abanikanda, NYJ RB
Tutu Atwell, LAR WR
Chris Rodriguez Jr., WAS RB
Michael Thomas, FA WR
Sam Howell, SEA QB
Brenden Rice, LAC WR
John Metchie III, HOU WR
Kareem Hunt, FA RB
Michael Carter, ARI RB
Jeff Wilson Jr., MIA RB
Jalen Tolbert, DAL WR
Tyler Scott, CHI WR
Eric Gray, NYG RB
Aidan O'Connell, LV QB
Johnny Wilson, PHI WR
Tre Tucker, LV WR
Zach Ertz, WAS TE
Colby Parkinson, LAR TE
JuJu Smith-Schuster, FA WR
Justice Hill, BAL RB
Jared Wiley, KC TE
Cam Akers, HOU RB
Luke Schoonmaker, DAL TE
Jamari Thrash, CLE WR
Pierre Strong Jr., CLE RB
Demarcus Robinson, LAR WR
Emari Demercado, ARI RB
Jaheim Bell, NE TE
Noah Gray, KC TE
Ainias Smith, PHI WR
Donovan Peoples-Jones, DET WR
D'Ernest Johnson, JAC RB
Hayden Hurst, LAC TE
Deuce Vaughn, DAL RB
Brevin Jordan, HOU TE
Jacoby Brissett, NE QB
Sean Tucker, TB RB
Allen Lazard, NYJ WR
Parker Washington, JAC WR
Kylen Granson, IND TE
Bo Melton, GB WR
Darnell Washington, PIT TE
Jordan Mason, SF RB
Isaiah Spiller, LAC RB
Irv Smith Jr., KC TE
Jerick McKinnon, FA RB
Dalvin Cook, FA RB
Bub Means, NO WR
Jeremy Ruckert, NYJ TE
Donald Parham Jr., LAC TE
Jauan Jennings, SF WR
Spencer Rattler, NO QB
Blake Watson, DEN RB
Tyquan Thornton, NE WR
Calvin Austin III, PIT WR
Adam Trautman, DEN TE
Jawhar Jordan, HOU RB
Chase Claypool, BUF WR
Charlie Jones, CIN WR
Trey Sermon, IND RB
Kenny Pickett, PHI QB
Jake Browning, CIN QB
Xavier Hutchinson, HOU WR
Logan Thomas, FA TE
Ryan Flournoy, DAL WR
Tommy Tremble, CAR TE
Tanner Hudson, CIN TE
Zach Evans, LAR RB
Tip Reiman, ARI TE
Mac Jones, JAC QB
Will Mallory, IND TE
Ronnie Rivers, LAR RB
AJ Barner, SEA TE
Desmond Ridder, ARI QB
Will Dissly, LAC TE
Jimmy Garoppolo, LAR QB
Trey Lance, DAL QB
Marquez Valdes-Scantling, BUF WR
Hunter Renfrow, FA WR
Dillon Johnson, CAR RB
Robert Woods, HOU WR
Brenton Strange, JAC TE
Jase McClellan, ATL RB
Frank Gore Jr., BUF RB
Deneric Prince, KC RB
Joshua Kelley, FA RB
Isaiah Hodgins, NYG WR
Terrace Marshall Jr., CAR WR
Foster Moreau, NO TE
Cordarrelle Patterson, PIT RB
Hendon Hooker, DET QB
Jake Bobo, SEA WR
Cole Turner, WAS TE
Drew Lock, NYG QB
Latavius Murray, FA RB
Allen Robinson II, NYG WR
Davis Allen, LAR TE
Van Jefferson, PIT WR
Elijah Higgins, ARI TE
Kyle Philips, TEN WR
Xavier Gipson, NYJ WR
Durham Smythe, MIA TE
Parris Campbell, PHI WR
David Bell, CLE WR
Chase Edmonds, TB RB
Jalen Coker, CAR WR
Casey Washington, ATL WR
Josh Oliver, MIN TE
Trenton Irwin, CIN WR
Tim Patrick, DEN WR
Keaontay Ingram, KC RB
Michael Pratt, GB QB
Kayshon Boutte, NE WR
Jha'Quan Jackson, TEN WR
Cody Schrader, SF RB
Cedrick Wilson Jr., NO WR
Zonovan Knight, DET RB
DeWayne McBride, MIN RB
Kenny McIntosh, SEA RB
Harrison Bryant, LV TE
Justin Watson, KC WR
Charlie Kolar, BAL TE
Jordan Whittington, LAR WR
Nelson Agholor, BAL WR
Joshua Dobbs, SF QB
Kalif Raymond, DET WR
Ryan Tannehill, FA QB
Kevin Harris, NE RB
Mason Rudolph, TEN QB
Johnny Mundt, MIN TE
Chris Evans, CIN RB
Joe Milton III, NE QB
Jameis Winston, CLE QB
Bailey Zappe, NE QB
Joe Flacco, IND QB
Zach Wilson, DEN QB
Leonard Fournette, FA RB
Mack Hollins, BUF WR
Rashaad Penny, FA RB
Kendall Milton, PHI RB
Lucas Krull, DEN TE
Marcus Mariota, WAS QB
Royce Freeman, DAL RB
Zack Kuntz, NYJ TE
Tyler Huntley, CLE QB
Kyle Trask, TB QB
Malik Davis, DAL RB
Tahj Washington, MIA WR
Dyami Brown, WAS WR
Jarrett Stidham, DEN QB
Trayveon Williams, CIN RB
Brandon Powell, MIN WR
Ty Johnson, BUF RB
Dallin Holker, NO TE
Peyton Hendershot, DAL TE
Nick Westbrook-Ikhine, TEN WR
Justyn Ross, KC WR
Jamison Crowder, WAS WR
Sterling Shepard, TB WR
DeeJay Dallas, ARI RB
Tyson Bagent, CHI QB
Michael Gallup, FA WR
Mecole Hardman Jr., KC WR
Carson Wentz, KC QB
Jordan Travis, NYJ QB
Craig Reynolds, DET RB
Boston Scott, LAR RB
Tanner McLachlan, CIN TE
Matt Breida, SF RB
Malik Willis, TEN QB
Dorian Thompson-Robinson, CLE QB
Tyrod Taylor, NYJ QB
Connor Heyward, PIT TE
Cooper Rush, DAL QB
Taylor Heinicke, ATL QB
Richie James Jr., FA WR
Quez Watkins, PIT WR
Derius Davis, LAC WR
Russell Gage, BAL WR
Brevyn Spann-Ford, DAL TE
Louis Rees-Zammit, KC RB
Keilan Robinson, JAC RB
Bryce Ford-Wheaton, NYG WR
Jaret Patterson, LAC RB
Teagan Quitoriano, HOU TE
Joe Parker, FA WR
Deon Jackson, NYJ RB
Isaiah McKenzie, NYG WR
Pharaoh Brown, SEA TE
Devin Duvernay, JAC WR
Ameer Abdullah, LV RB
Tejhaun Palmer, ARI WR
Brock Wright, DET TE
KJ Hamler, BUF WR
Tyler Goodson, IND RB
Ray-Ray McCloud III, ATL WR
JaMycal Hasty, NE RB
Salvon Ahmed, MIA RB
Robert Tonyan, MIN TE
Shi Smith, FA WR
Cameron Latu, SF TE
John Bates, WAS TE
Tyrion Davis-Price, PHI RB
Albert Okwuegbunam Jr., PHI TE
Austin Hooper, NE TE
Nyheim Hines, CLE RB
Kenyan Drake, FA RB
Velus Jones Jr., CHI WR
Byron Pringle, WAS WR
Mo Alie-Cox, IND TE
Daijun Edwards, PIT RB
Braxton Berrios, MIA WR
Marvin Jones Jr., FA WR
Robbie Chosen, SF WR
Laviska Shenault Jr., SEA WR
Marlon Mack, FA RB
Darrell Henderson Jr., FA RB
James Robinson, NO RB
Anthony Gould, IND WR
Jalen Guyton, LV WR
"""
